// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/icon-48.png"
    | "/icon.png"
    | "/icons/icon-128.png"
    | "/icons/icon-16.png"
    | "/icons/icon-19.png"
    | "/icons/icon-256.png"
    | "/icons/icon-32.png"
    | "/icons/icon-38.png"
    | "/icons/icon-48.png"
    | "/icons/icon-512.png"
    | "/logo.svg"
    | "/popup.html"
    | "/test-demo.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
